build: 
	python3 main.py $(limit) >> run_log.log 

clean: 
	rm -f ../*.json
	rm -f ../reblog_data/*.json
	rm -f ../*.pdf
	rm -f ../account_data/*.json 
	rm -f ../status_data/*.json 
	rm -f ./run_log.log